pipeline {

    agent { node { label 'docker' } }
    
    parameters {
        choice(name: 'VERSION', choices: ['1.1.0', '1.2.0', '1.3.0'], description: '')
        booleanParam(name: 'executeTests', defaultValue: true, description: '')
   
    stages {
        stage('Init') {
            steps {
                echo 'Listing Docker Swarm stacks:'
                sh 'ls -lha'
                sh 'pwd'
                sh 'docker stack ls'
                script {
                    gv = load 'script.groovy'
            }
        }
        stage('Build') {
            steps {
                script {
                    gv.buildApp()   
                }
            }
        }
        stage('Test') {
            when {
                expression {
                    params.executeTests
                }
            }
            steps {
                script {
                    gv.testApp()
                }
            }
        }
        stage('Deploy') {
            steps {
                script {
                    gv.executeTests()   
                }
            }
        }
    }
}
