pipeline {

    agent any

    stages {
        stage('Git Checkout') {
            steps {
                echo 'Listing Docker Swarm stacks:'
                sh 'ls -lha'
                sh 'pwd'
            }
        }
        stage('Build') {
            steps {
                echo 'Building...'
            }
        }
        stage('Tests') {
            steps {
                echo 'Testing...'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying...'
            }
        }
    }
}